# Generated by Django 5.0.6 on 2024-05-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_weight_uav_air_residence_time_alter_uav_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='category',
            field=models.CharField(choices=[('Plane', 'Plane'), ('Missile', 'Missile'), ('Uav', 'Uav')], max_length=100),
        ),
    ]
